Adnane signup
uiowaSEP2024/001_DisAv pull request #89
Opened 2024-02-21 20:47 UTC by aezouhri

<!Pull Request Template>

## Description

<!Please provide a summary of the changes you have made. Include any relevant motivation and context. Mention any dependencies that are required for this change.>
Created the user dashboard. Currently have the preferences on the dashboard ensuring it is loaded properly and working properly.

## Tests
Tests cover the interaction of the buttons based of the data from mocked db objects.

## UI Changes
![image](https://github.com/uiowaSEP2024/001_DisAv/assets/95724930/8a94798b-2719-4401-a5ab-ca969cfdd0a6)

## Issues
#47 #66 

<!Mention any issues or bugs this PR addresses or fixes. Link any related issues.>

## Additional Notes
_Add any other information about the PR here._
Need to work putting the preferences on pop-up window on first sign up. Otherwise they will be located on the settings page.
---

2024-02-21 22:03 UTC, aezouhri commented
Need help, some of the tests are not passing. Can someone assist ?

2024-02-21 22:39 UTC, saanbe16 commented
> Need help, some of the tests are not passing. Can someone assist ?

I'll look into this

2024-02-22 04:17 UTC, aezouhri reviewed
Thanks for looking into this!

2024-02-22 04:35 UTC, saanbe16 requested changes

2024-02-22 04:35 UTC, saanbe16 commented on web/src/components/Login.js
> -        }, "*");
@aezouhri This code needs to be put back, in order for the extension login to work, please put it back and re push, If you put it somewhere else let me know where it is so i can double check that the logic works

2024-02-22 04:55 UTC, saanbe16 approved these changes
This is good to merge now

2024-02-22 04:56 UTC, merged